### ISSUE TITLE
Trying to get reactive-component-loader to work

### ISSUE THREAD

**Issue by pmcochrane** [wishtack/wishtack-steroids#160]
Hi. Just trying out your component to attempt to load components from other lazily loaded modules into a lazily loaded module. I'm having a few gremlins trying to get it to work.

The readme does not show import declarations so I am assuming they should be for both appmodule and the feature module:
`
import { ReactiveComponentLoaderModule } from '@wishtack/reactive-component-loader';
`

In my feature module, I'm adding in the imports array:
```
ReactiveComponentLoaderModule.withModule({
	moduleId: 'patientRecord',
	loadChildren: '../patientRecord/patientRecord.module#PatientRecordModule' ,
}),
```
I do not know what the ./+ does in your example in the readme. For my app, I'm looking to load a module from a relative path in the folder structure.

In the component that I wish to use <wt-lazy>:
```
<wt-lazy [location]="patientRecordComponentLocation" [inputs]="{bannerOptions: patientBannerOptions}"></wt-lazy>
```
I am unsure if I need the closing </wt-lazy> or not.

I have defined in the component:
```
patientRecordComponentLocation = {
	moduleId: 'patientRecord',
	selector: 'patient-record',
};
```

Unfortunately, when I try to run the app I get an error:
```
Uncaught SyntaxError: Unexpected token {
```
This error is referencing the import line in the ng-dynamic-component library that you depend upon.
Angular basically does not start at all.
```
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                     //
// node_modules/ng-dynamic-component/dynamic/io.service.js                                                             //
//                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                       //
/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes,extraRequire,missingReturn,uselessCode} checked by tsc
 */
import { ComponentFactoryResolver, Injectable, KeyValueDiffers, } from '@angular/core';

```

Any ideas about what can be causing this?

**Comment by pmcochrane** [comment]
Looking more into this, the error disappear and the app starts properly if I comment  the import  of ReactiveComponentLoaderModule.forRoot() in the appModule.

**Comment by yjaaidi** [comment]
Hi Paul!

Thank you for your feedback!

I just updated the Readme by adding the missing import and removing the `+` symbol that could be confusing _(it's a naming convention for lazy loaded modules)_.

Could you please tell me more about Angular and `ng-dynamic-component` versions you are using?

Can you reproduce the problem on Stackblitz?

Thank you in advance.

Younes
