### ISSUE TITLE
ng g results in 'specified component does not exist'

### ISSUE THREAD

**Issue by MHacker9404** [wishtack/wishtack-steroids#174]
trying to create new SCAM - executing 'yarn ng g @wishtack/schematics:scam CustomEvents' results in a Specified module 'customevents' does not exist.

**Comment by yjaaidi** [comment]
Hi Phil, thank you for the discovery.
In fact, the schematic doesn't handle PascalCase or camelCase names for the moment.
Meanwhile I fix this, can you try this out `yarn ng g @wishtack/schematics:scam custom-events`?

**Comment by yjaaidi** [comment]
Hi Phil,

The issue has now been fixed in version 1.1.1. It should work if you upgrade `@wishtack/schematics`.

Thanks for reporting.

**Comment by MHacker9404** [comment]
Works like a charm - thanks

**Comment by yjaaidi** [comment]
Great! Thanks for the feedback.
