### ISSUE TITLE
does not obey --routing

### ISSUE THREAD

**Issue by MHacker9404** [wishtack/wishtack-steroids#175]
--routing does not add a routing module

**Comment by yjaaidi** [comment]
Hi @MHacker9404,

Sorry for responding so late but I don't think that the SCAM generator should be used to generate routing modules.

Can you share a more precise scenario?

Thank you in advance.

Younes

**Comment by MHacker9404** [comment]
Let's say you have a SCAM that will be routing lazy loaded with child components?

**Comment by yjaaidi** [comment]
I guess it's better to avoid mixin a scam with a routing module. It should be either one or the other.
