### ISSUE TITLE
Can't resolve ng-dynamic-component

### ISSUE THREAD

**Issue by rmalvarado1805** [wishtack/wishtack-steroids#178]
I think there is a problem with the package, I get an error in angular cli that it cannot resolve ng-dynamic-component and @whistack/rxscavenger, I don't think there is an error with my code, because I'm not using it, I'm just importing the module
![image](https://user-images.githubusercontent.com/33607941/57338241-409df100-70f2-11e9-9ac3-e076aa21ae8e.png)

**Comment by rmalvarado1805** [comment]
problem solved, i had to install ng-dynamic-component and @wistach/rx-scavenger with yarn, I don't know if this is expected behavior.

**Comment by yjaaidi** [comment]
Hi! Sorry for the inconvenience.
I just made an upgrade and since 0.2.7, you don't have to install ng-dynamic-component and @wistach/rx-scavenger as they are bundled with `@wishtack/reactive-component-loader`.
