### ISSUE TITLE
es5 - compatible / ng-dynamic-component as dependency

### ISSUE THREAD

**Issue by Sebush** [wishtack/wishtack-steroids#180]
- transpile the whole package (reactive-component-loader) to es5 to use it in ie9/11 (supported by angular)
- move the devDependency "ng-dynamic-component" (ideally well transpiled to es5 too) to the dependency to avoid install it by myself

or provide the ts-sources in the npm-repo to deep-import the ts-files and transpile by angular itself

**Comment by roseyda** [comment]
+1 not working on IE11 as it use ng-dynamic-component es2015

**Comment by yjaaidi** [comment]
Hi!
I just made an update (0.2.7) to add ng-dynamic-component and @wishtack/rx-scavenger as dependencies instead of peer dependencies so you don't have to install them separately anymore.
Not sure if it fixes IE9/11 issue as I didn't check that out yet.

Let me know if this helps.

Thank you.

**Comment by roseyda** [comment]
Hi,
First, thanks for this quick update.
I'll give a try tomorow morning and let you know.

Thanks to you for this gret library!!!

regards

**Comment by roseyda** [comment]
Hi,

I just tested:
- There is no more issue for missing dependencies, everything is properly installed :-)
- The issue on IE11 is still present (ng-dynamic-component es2015 code included in my vendor.js) :-(

=> The issue maybe come from ng-dynamic-component, but this is strange as the es5 bundle is available in ng-dynamic-component.
=> Why do Angular does not take this bundle but the es2015 instead ???
=> I just add a comment on a similar issue on ng-dynamic-component gitHub repo: https://github.com/gund/ng-dynamic-component/issues/245

**Comment by yjaaidi** [comment]
Hi @roseyda,
Thank you for your feedback. Could you please share your `tsconfig.json` & `src/tsconfig.app.json`?
Thanks!

**Comment by roseyda** [comment]
Hi @yjaaidi,

Hereafter are the content of the files:
tsconfig.json:

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2018", "dom"],
    "paths": {
      "@app/*": ["src/app/*"],
      "@feature/*": ["src/app/feature*"],
      "@session-store/*": ["src/app/shared/session-store/*"],
      "@environment/*": ["src/environments/*"]
    }
  }
}

and the tsconfig.app.json:
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

Original files attach in the linked zip.

Reards

[tsconfig.zip](https://github.com/wishtack/wishtack-steroids/files/3199993/tsconfig.zip)

**Comment by roseyda** [comment]
For testing, I also try 2 things:
- delete the ng-dynamyc-component.es2015.js in node_modules/ng-dynamyc-component/bundle
- replace the ng-dynamyc-component.es2015.js content by the content of ng-dynamyc-component.es5.js

In both cases, the class IOService is still present in vendor.js :-(

**Comment by yjaaidi** [comment]
I guess this is related to this issue https://github.com/gund/ng-dynamic-component/issues/225.
I might get rid of `wtLazy` structural directive (but still keep the `wt-lazy` component of course) to fix the issue.

**Comment by roseyda** [comment]
Hi @yjaaidi,
Yes both issue seems related.
If removing the wtlazy directive solve the issue, it would be a nice solution for me as I use the wt-lazy component :-)
But maybe others prefer using the directive...
As it's your libray, I can't take the decision.
Anyway, thanks for your great job and for taking time investigating this issue.

**Comment by roseyda** [comment]
Hi @yjaaidi,
Please let me know if you deploy a version of the lib working on IE.
Thanks in advance.
Regards

**Comment by yjaaidi** [comment]
Thank you for your feedback.
I guess nobody is using `wtLazy` structural directive as I didn't document it on purpose. I was waiting to find some time to produce a cleaner implementation. 
I ended up removing it which was faster. Hope it helps 😊

**Comment by roseyda** [comment]
Hi @yjaaidi ,

I just tested it OK on IE11.
Thanks again for investigating and quickly solving this issue.

Regards

**Comment by yjaaidi** [comment]
👌 thank you for using reactive component loader and for your feedback.

Younes

**Comment by Sebastian-Haehnlein-Intershop** [comment]
problem solved, thank u all
