### ISSUE TITLE
After upgrading to 1.1.0 i'm getting scavenger error

### ISSUE THREAD

**Issue by doronsever** [wishtack/wishtack-steroids#193]
After upgrading to 1.1.0 we are getting this error: 

`Module not found: Error: Can't resolve 'core-js/es/map' in '../node_modules/@wishtack/rx-scavenger/dist'`

Might also help: 

`Field 'browser' doesn't contain a valid alias configuration`

It also happens when upgrading to 1.0.1

After downgrading to 1.0.0 everything seems to work.
We are on the latest stable Angular (8.2.12)

**Comment by kmanev073** [comment]
@doronsever `npm install --save core-js@3` This will save you ;)

**Comment by yjaaidi** [comment]
Thank you @doronsever for the question and thank you @kmanev073 for your help!
In fact, `@wishtack/scavenger` now needs `core-js>=3.0.0` as you can see here : https://github.com/wishtack/wishtack-steroids/blob/b9f84e21b3427ce9adc83df0bca4363c6e12ed3a/packages/rx-scavenger/package.json#L30

You should've had an incompatible peer dependency warning when installing your dependencies.

I am closing the issue as it seems to be solved. Feel free to open a new one if you have any question or improvement idea.
